dist: trusty
language: cpp
compiler:
 - gcc

addons:
 apt:
  sources:
   - george-edison55-precise-backports # cmake 3.2.3
   - ubuntu-toolchain-r-test
  packages:
   - cmake
   - cmake-data
   - libfftw3-dev   
   - libgtest-dev
   - libboost1.55-all-dev

branches:
 only:
  - master
  - v2.4.X
  - v2.4.0
  - v2.5.0
  - v2.5.3
  - ipp-2017-u3

before_script:
 - mkdir build
 - cd build
 - cmake -Dtest=yes ../

script:
 - make tests
 - ctest -V

