dist: trusty
language: cpp
compiler:
 - gcc

addons:
 apt:
  sources:
   - george-edison55-precise-backports # cmake 3.2.3
   - ubuntu-toolchain-r-test
  packages:
   - cmake
   - cmake-data
   - libfftw3-dev   
   - libgtest-dev
   - libboost1.55-all-dev

before_install:
 - sudo wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
 - sudo tar xf release-1.8.0.tar.gz
 - cd googletest-release-1.8.0
 - sudo cmake -DBUILD_SHARED_LIBS=ON .
 - sudo make
 - sudo cp -a googletest/include/gtest /usr/include
 - sudo cp -a ./googlemock/gtest/libgtest_main.so ./googlemock/gtest/libgtest.so /usr/lib/
 - cd "${TRAVIS_BUILD_DIR}"

branches:
 only:
  - master
  - v2.4.X
  - v2.4.0
  - v2.5.0


before_script:
 - mkdir build
 - cd build
 - cmake -Dtest=yes ../

script:
 - make tests
 - ctest -V

